#!/bin/bash

while getopts ":c:m:v:h" opt; do
  case $opt in
    c) arg1="$OPTARG";;
    m) arg2="$OPTARG";;
    v) arg3="$OPTARG";;
    h) echo "Usage: sh_comand [-c] [-m] [-v]"
        echo "  -c - command"
            echo "     -c get_json"
                echo "          -m - monitorin_sustem"
                    echo "              -m glonass"
                        echo "                  -v objects "
                        echo "                  -v agents "
                        echo "                  -v users "
                        echo "                  -v merge "
                    echo "              -m fort"
                        echo "                  -v objects "
                        echo "                  -v companies "
                        echo "                  -v groups_companies "
                        echo "                  -v groups_users "
                        echo "                  -v users "
                        echo "                  -v merge "
                    echo "              -m whost"
                        echo "                  -v units "
                        echo "                  -v users "
                        echo "                  -v merge "
                    echo "              -m wlocal"
                        echo "                  -v units "
                        echo "                  -v users "
                        echo "                  -v merge "
                    echo "              -m scout"
                        echo "                  -v units "
                    echo "              -m era"
        echo "  -v - variable"
        echo "  -h - help"

        exit 0;;
    \?) echo "Неверный флаг: -$OPTARG" >&2;;
  esac
done

source ~/bitrix_work/env/bin/activate
python3 ~/bitrix_work/py_comands.py $arg1 $arg2 $arg3
deactivate
